name: daapfl-ra
channels: [pytorch, nvidia, conda-forge, defaults]
dependencies:
  - python=3.11
  - pip=24.0
  - cuda-version=12.1
  - cudnn=8.9.*
  - geos=3.12.*
  - libstdcxx-ng>=12
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.3.1
      - torchvision==0.18.1
      - segmentation-models-pytorch==0.3.4
      - timm==0.9.7
      - flwr[simulation]==1.9.0
      - ray==2.10.0
      - numpy==1.26.4
      - pandas==2.2.2
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - opencv-python==4.10.0.84
      - pillow==10.3.0
      - shapely==2.0.4
      - albumentations==1.4.10
      - grad-cam==1.5.0
      - matplotlib==3.9.1
      - wandb==0.17.5
      - pyyaml==6.0.1
      - tqdm==4.66.4
